### ISSUE TITLE
Ежедневные задания (не квест)

### ISSUE THREAD

**Issue by glig7** [glig7/OrthrusOnline#94]

**Comment by Dedul9** [comment]
Список ежедневных задач (задача выбирается рандомно):

=== 1 ===
- Одержать победу над 5 тренерами
- Победить 150 диких покемонов
=== 2 ===
- Получить 10 яиц покемонов
=== 3 ===
-
=== 4 ===
=== 5 ===
=== 6 ===
=== 7 ===
=== 8 ===
=== 9 ===
=== 10 ===
=== НАГРАДА ===
